#!/usr/bin/env bash
set -uo pipefail
IFS=$'\n\t'

# Load utility methods
. "$ROOT_DIR/utils"

function cleanup() {
    echo "Cleaning up..."
}

if [[ "${BASH_SOURCE[0]}" = "$0" ]]; then
    trap cleanup EXIT

    # Check if python3 is installed
    if ! command -v python3 &> /dev/null; then
        info "Python3 is not installed. Please install Python3 first."
        if [[ "$OSTYPE" == "darwin"* ]]; then
            info "Installing Python3 using Homebrew"
            brew install python
        elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
            info "Installing Python3 using apt-get"
            sudo apt-get update
            sudo apt-get install -y python3
        else
            fatal "Unsupported operating system: $OSTYPE"
        fi
    fi

    # Create a virtual environment
    python3 -m venv .venv
    source .venv/bin/activate
    pip install ansible

    ansible-galaxy install -r kubernetes-playbook/requirements.yml
fi