#!/usr/bin/env bash
set -uo pipefail
IFS=$'\n\t'

# Load utility methods
# shellcheck disable=SC1091
. "$ROOT_DIR/utils"

function cleanup() {
    echo "Cleaning up..."
}

if [[ "${BASH_SOURCE[0]}" = "$0" ]]; then
    trap cleanup EXIT

    # shellcheck disable=SC2154
    path=$(${cli_name_app} zoptions rc read .dir)
    cd "$path" || fatal "Failed to cd to $path"

    # Check if python3 is installed
    if ! command -v python3 &> /dev/null; then
        info "Python3 is not installed. Please install Python3 first."
        if [[ "$OSTYPE" == "darwin"* ]]; then
            info "Installing Python3 using Homebrew"
            brew install python
        elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
            info "Installing Python3 using apt-get"
            sudo apt-get update
            sudo apt-get install -y python3
        else
            fatal "Unsupported operating system: $OSTYPE"
        fi
    fi

    # Create a virtual environment
    if [[ ! -d .venv ]]; then
        python3 -m venv .venv
    else
        info "Virtual environment already exists."
    fi

    # shellcheck disable=SC1091
    source .venv/bin/activate

    pip install --upgrade pip
    pip install ansible --no-input
    pip install ansible-creator --no-input

    #ansible-galaxy install -r kubernetes-playbook/requirements.yml
fi
