#!/usr/bin/env bash
set -uo pipefail
IFS=$'\n\t'

# Load utility methods
# shellcheck disable=SC1091
. "$ROOT_DIR/utils"

function cleanup() {
    echo "Cleaning up..."
}

if [[ "${BASH_SOURCE[0]}" = "$0" ]]; then
    trap cleanup EXIT

    # Check if vagrant is installed
    if ! command -v vagrant &> /dev/null; then
        info "Vagrant is not installed. Please install Vagrant first."
        if [[ "$OSTYPE" == "darwin"* ]]; then
            info "Installing Vagrant using Homebrew"
            brew install vagrant
        elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
            info "Installing Vagrant using apt-get"
            wget -O - https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
            echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
            sudo apt-get update && sudo apt-get install -y vagrant
        else
            fatal "Unsupported operating system: $OSTYPE"
        fi
    fi
fi
