- name: Disable swap temporarily
  ansible.builtin.shell: swapoff -a
  become: true

- name: Disable swap permanently
  ansible.builtin.mount:
    name: swap
    fstype: swap
    state: absent
  become: true

- name: Ensure systemd-timesyncd is installed
  ansible.builtin.package:
    name: systemd-timesyncd
    state: present
  become: true

- name: Ensure systemd-timesyncd is started and enabled
  ansible.builtin.service:
    name: systemd-timesyncd
    state: started
    enabled: true
  become: true

- name: Force time synchronization
  ansible.builtin.command: timedatectl set-ntp true
  become: true