---
- name: Apply Flannel CNI
  ansible.builtin.command: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
  become: true
  become_user: "{{ ansible_user }}"
  environment:
    KUBECONFIG: "{{ ansible_env.HOME }}/.kube/config"
  retries: 5
  delay: 10
  until: result.rc == 0
  register: result
  ignore_errors: true

- name: Ensure Flannel is deployed successfully
  ansible.builtin.fail:
    msg: "Failed to deploy Flannel CNI."
  when: result.rc != 0