---
- name: Join Kubernetes Cluster
  command: kubeadm join {{ hostvars['master']['ip'] }}:6443 --token {{ kubeadm_token }} --discovery-token-ca-cert-hash sha256:{{ kubeadm_hash }}
  args:
    warn: false
  when: inventory_hostname in groups['slaves']