---
- name: Prep system operations
  hosts: all
  become: yes
  vars_files:
    - vars/main.yml
  roles:
    - system

- name: Kubernetes Cluster Setup
  hosts: all
  become: yes
  vars_files:
    - vars/main.yml
  roles:
    - container-runtime
    - kubernetes

- name: Initialize Kubernetes Master
  hosts: master
  become: no
  roles:
    - kube_master
  vars:
    become: yes

- name: Install Flannel CNI
  hosts: master
  become: no
  roles:
    - flannel
  vars:
    become: yes

- name: Join Worker Nodes to Cluster
  hosts: workers
  vars_files:
    - vars/main.yml
  become: yes
  roles:
    - kube_worker
