---
- name: Deploy Kubernetes
  hosts: master_vagrant
  roles:
    - common
    - containerd
    - kubernetes

# - name: Configure Kubernetes Master
#   hosts: master_vagrant
#   roles:
#     - master

# - name: Join Kubernetes Workers
#   hosts: slaves_vagrant
#   roles:
#     - worker
