---
- name: Deploy Kubernetes Cluster
  hosts: all
  become: yes
  roles:
    - common
    - container-runtime
    - networking

- name: Initialize Kubernetes Master
  hosts: masters
  become: yes
  roles:
    - kubernetes-master

- name: Join Kubernetes Nodes
  hosts: slaves
  become: yes
  roles:
    - kubernetes-node