---
- name: Deploy Kubernetes Cluster
  hosts: all
  become: yes

  roles:
    - common
    - containerd
    - kubernetes

- name: Configure Kubernetes Master
  hosts: masters
  become: yes

  roles:
    - master

- name: Join Kubernetes Workers
  hosts: workers
  become: yes

  roles:
    - worker