---
- name: Prepare all nodes
  hosts: all
  become: true
  roles:
    - system
    - container-runtime
    - kubernetes

- name: Initialize Kubernetes Master
  hosts: masters
  become: true
  roles:
    - kube_master

- name: Join Kubernetes Slaves
  hosts: slaves
  become: true
  roles:
    - kube_node

- name: Deploy Network Plugin (Flannel)
  hosts: masters
  become: true
  roles:
    - flannel