---
- name: Prep system operations
  hosts: all
  become: yes
  vars_files:
    - vars/main.yml
  roles:
    - system

- name: Kubernetes Cluster Setup
  hosts: all
  become: yes
  vars_files:
    - vars/main.yml
  roles:
    - docker
    - kubernetes

- name: Initialize Kubernetes Master
  hosts: master
  become: yes
  roles:
    - kube_master

- name: Install Calico CNI
  hosts: master
  become: yes
  roles:
    - calico

- name: Join Worker Nodes to Cluster
  hosts: workers
  become: yes
  roles:
    - kube_worker
