---
- name: Deploy Kubernetes
  hosts: masters
  roles:
    - common
    - containerd
    - kubernetes

- name: Configure Kubernetes Master
  hosts: masters
  roles:
    - master

- name: Join Kubernetes Workers
  hosts: slaves
  roles:
    - worker
