---
- name: Deploy Vagrant VMs
  hosts: local
  roles:
    - vagrant

# - name: Deploy Kubernetes
#   hosts: vm
#   roles:
#     - common
#     - containerd
#     - kubernetes

# - name: Configure Kubernetes Master
#   hosts: masters_vagrant

#   roles:
#     - master

# - name: Join Kubernetes Workers
#   hosts: workers_vagrant
#
#   roles:
#     - worker
