---
- name: Deploy Kubernetes Cluster
  hosts: all
  become: yes

  vars:
    kubernetes_version: "1.31"
    pod_network_cidr: "192.168.0.0/16"

  roles:
    - common
    - docker
    - kubernetes

- name: Configure Kubernetes Master
  hosts: masters
  become: yes

  roles:
    - master

- name: Join Kubernetes Workers
  hosts: workers
  become: yes

  roles:
    - worker