---
- name: Install dependencies
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
    state: present
    update_cache: yes

- name: Add Kubernetes apt key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Add Kubernetes repository
  apt_repository:
    repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
    state: present

- name: Install Kubernetes components
  apt:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present
    update_cache: yes

- name: Disable swap
  command: swapoff -a
  when: ansible_swaptotal_mb > 0

- name: Remove swap from fstab
  lineinfile:
    path: /etc/fstab
    regexp: '^(\s*)([^#\n]+\s+)(\w+\s+)swap(\s+.*)$'
    line: '# \1\2\3swap\4'
    backrefs: yes

- name: Initialize Kubernetes cluster
  command: kubeadm init --config=/tmp/kubeadm-config.yaml
  args:
    creates: /etc/kubernetes/admin.conf
  when: inventory_hostname == groups['masters'][0]

- name: Copy kubeconfig for root user
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /root/.kube/config
    remote_src: yes
  when: inventory_hostname == groups['masters'][0]

- name: Install Weave Net CNI
  command: kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"
  when: inventory_hostname == groups['masters'][0]

- name: Get join command
  command: kubeadm token create --print-join-command
  register: join_command
  when: inventory_hostname == groups['masters'][0]

- name: Join workers to the cluster
  command: "{{ hostvars[groups['masters'][0]]['join_command'].stdout }}"
  when: inventory_hostname in groups['workers']