---
- name: Debug - Check API server status
  ansible.builtin.debug:
    msg: "Checking API server at {{ ansible_host }}:6443"

- name: Wait for Kubernetes API to become available
  ansible.builtin.wait_for:
    host: "{{ ansible_host }}"
    port: 6443
    timeout: 10
    state: started
  register: wait_result
  
- name: Debug - API server wait result
  ansible.builtin.debug:
    var: wait_result
    
- name: Verify kubectl can connect
  ansible.builtin.command: kubectl get nodes
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  register: kubectl_test
  ignore_errors: true

- name: Debug - kubectl test result
  ansible.builtin.debug:
    var: kubectl_test

- name: Download Calico manifest
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/projectcalico/calico/v3.29.1/manifests/calico.yaml
    dest: /tmp/calico.yaml
    mode: '0644'

- name: Apply Calico manifest with kubectl
  ansible.builtin.command: kubectl apply -f /tmp/calico.yaml --validate=false
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  register: calico_result
  retries: 5
  delay: 20
  until: calico_result.rc == 0