---
- name: Build and push images to the registry
  hosts: master
  become: yes
  tasks:
    - name: Install required packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
        state: present
        update_cache: yes

    - name: Add Docker's official GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker apt repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present

    - name: Install Docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present

    - name: Configure Docker to trust the insecure registry
      copy:
        dest: /etc/docker/daemon.json
        content: |
          {
            "insecure-registries": ["localhost:32000"]
          }

    - name: Restart Docker
      systemd:
        name: docker
        state: restarted

    - name: Copy src folder to the remote hosts
      synchronize:
        src: ../src
        dest: /home/{{ ansible_user }}/
        recursive: yes
        delete: yes
        rsync_opts:
          - "--chown={{ ansible_user }}:{{ ansible_user }}"

    - name: Build and tag Docker images
      shell: |
        docker build -t localhost:32000/mysql server/mysql
        docker build -t localhost:32000/maven plugin/maven
        docker build -t localhost:32000/gradle plugin/gradle
        docker build -t localhost:32000/game-server -f server/common/game-server-files/Dockerfile .
        docker build -t localhost:32000/lobby -f server/common/lobby-files/Dockerfile .
        docker build -t localhost:32000/proxy -f server/common/proxy-files/Dockerfile .
      args:
        chdir: /home/{{ ansible_user }}/src

    - name: Push images to the registry
      shell: |
        docker push localhost:32000/mysql
        docker push localhost:32000/maven
        docker push localhost:32000/gradle
        docker push localhost:32000/game-server
        docker push localhost:32000/lobby
        docker push localhost:32000/proxy
