---
- name: Deploy Docker registry
  hosts: master
  tasks:
    - name: Install kubernetes Python library
      pip:
        name: kubernetes
        state: present
        executable: pip3

    - name: Create registry namespace
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: registry

    - name: Deploy registry deployment
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: registry
            namespace: registry
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: registry
            template:
              metadata:
                labels:
                  app: registry
              spec:
                containers:
                  - name: registry
                    image: registry:2
                    ports:
                      - containerPort: 5000

    - name: Expose registry service
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: registry
            namespace: registry
          spec:
            selector:
              app: registry
            ports:
              - protocol: TCP
                port: 5000
                targetPort: 5000