---
- name: Create directory for Kubernetes APT keyring
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download Kubernetes APT repository key
  ansible.builtin.get_url:
    url: https://pkgs.k8s.io/core:/stable:/v1.28/deb/Release.key
    dest: /tmp/kubernetes-release.key
    mode: '0644'

- name: Dearmor Kubernetes APT repository key
  ansible.builtin.command:
    cmd: gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg /tmp/kubernetes-release.key
    creates: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
  args:
    removes: /tmp/kubernetes-release.key

- name: Add Kubernetes APT repository
  ansible.builtin.apt_repository:
    repo: 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.28/deb/ /'
    filename: kubernetes
    state: present

- name: Add Docker’s official GPG key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Set up the Docker repository
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
    state: present

- name: Update APT package index after adding repositories
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install Docker Engine
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present

- name: Install Kubernetes packages
  ansible.builtin.apt:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present

- name: Hold Kubernetes packages at current version
  ansible.builtin.command:
    cmd: apt-mark hold kubelet kubeadm kubectl
  args:
    warn: false
  when: ansible_os_family == "Debian"

- name: Verify Kubernetes packages are held
  ansible.builtin.command:
    cmd: apt-mark showhold
  register: held_packages
  changed_when: false

- name: Debug held packages
  debug:
    msg: "Held packages: {{ held_packages.stdout_lines }}"
  when: "'kubelet' in held_packages.stdout or 'kubeadm' in held_packages.stdout or 'kubectl' in held_packages.stdout"