---
- name: Install containerd
  ansible.builtin.apt:
    name:
      - lsb-release
      - socat
      - containerd.io
    state: present
    update_cache: true

- name: Create containerd config directory
  ansible.builtin.file:
    path: /etc/containerd
    state: directory
    mode: '0755'

- name: Configure containerd
  ansible.builtin.template:
    src: containerd_config.toml.j2
    dest: /etc/containerd/config.toml
    mode: '0644'
  notify: "Restart containerd"

- name: Configure kubelet to use containerd
  ansible.builtin.lineinfile:
    path: /etc/default/kubelet
    line: 'KUBELET_EXTRA_ARGS=--container-runtime=remote --container-runtime-endpoint=unix:///var/run/containerd/containerd.sock'
    create: true
    mode: '0644'

- name: Restart kubelet
  ansible.builtin.systemd:
    name: kubelet
    state: restarted
    daemon_reload: true
