---
- name: Install containerd
  ansible.builtin.apt:
    name:
      - lsb-release
      - socat
      - containerd.io
    state: present
    update_cache: true

- name: Create containerd config directory
  ansible.builtin.file:
    path: /etc/containerd
    state: directory
    mode: '0755'

- name: Configure containerd
  ansible.builtin.template:
    src: containerd_config.toml.j2
    dest: /etc/containerd/config.toml
    mode: '0644'
  notify: Restart containerd

- name: Configure kubelet to use containerd
  ansible.builtin.template:
    src: kubelet.j2
    dest: /etc/default/kubelet
    mode: '0644'
  notify: Restart kubelet
