version: "3.7"
services:
  lobby:
    build: ./lobby
    volumes:
      - mc-data:/data

  srv1:
    build: ./srv1

  proxy:
    build: ./proxy
    ports:
      - "25565:25577"
    volumes:
      - proxy-data:/server

volumes:
  mc-data:
  proxy-data: