# --------------------------------------
# -- Init master k8s node
# --------------------------------------
---
- name: Check if Kubernetes has already been initialized
  stat:
    path: /etc/kubernetes/admin.conf
  register: kubernetes_init_stat

- name: Create config file from template
  template:
    src: master-node.j2
    dest: "/tmp/init-config.yaml"
  register: kubernetes_init_config
  when: kubernetes_init_config is not defined

- name: Initialize Kubernetes master with kubeadm init.
  become: true
  command: >
    kubeadm init --config /tmp/init-config.yaml
  register: kubeadmin_init
  when: not kubernetes_init_stat.stat.exists

- name: Ensure .kube directory exists.
  file:
    path: "~/.kube"
    state: directory
    mode: 0755

- name: Symlink the kubectl admin.conf to ~/.kube/config
  file:
    src: /etc/kubernetes/admin.conf
    dest: "~/.kube/config"
    state: link
    mode: 0644

- name: Storing config on the local machine
  ansible.builtin.fetch:
    src: /etc/kubernetes/admin.conf
    dest: ./
    flat: yes

- name: Configure Flannel networking.
  command: "{{ item }}"
  with_items:
    - kubectl apply -f {{ kubernetes_flannel_manifest_file_rbac }}
    - kubectl apply -f {{ kubernetes_flannel_manifest_file }}
  register: flannel_result
  changed_when: "'created' in flannel_result.stdout"

- name: Get the kubeadm join command.
  command: kubeadm token create --print-join-command
  changed_when: false
  register: kubernetes_join_command_result
