# --------------------------------------
# -- Init master k8s node
# --------------------------------------
---
- name: Check if Kubernetes has already been initialized
  stat:
    path: /etc/kubernetes/admin.conf
  register: kubernetes_init_stat

- name: Create config file from template
  template:
    src: master-node.j2
    dest: "/tmp/init-config.yaml"
  register: kubernetes_init_config
  when: kubernetes_init_config is not defined

- name: Reload systemd daemon
  systemd:
    daemon_reload: yes

- name: Stop kubelet service
  systemd:
    name: kubelet
    state: stopped

- name: Restart containerd service
  systemd:
    name: containerd
    state: restarted

- name: Initialize Kubernetes master with kubeadm init.
  become: true
  command: >
    kubeadm init --config /tmp/init-config.yaml
  register: kubeadmin_init
  when: not kubernetes_init_stat.stat.exists

- name: Ensure .kube directory exists
  file:
    path: "/home/{{ ansible_user }}/.kube"
    state: directory
    mode: '0755'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Copy admin.conf to user's kube config
  copy:
    src: /etc/kubernetes/admin.conf
    dest: "/home/{{ ansible_user }}/.kube/config"
    mode: '0644'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    remote_src: yes

- name: Storing config on the local machine
  ansible.builtin.fetch:
    src: /etc/kubernetes/admin.conf
    dest: ./
    flat: yes

- name: Configure Flannel networking.
  command: "{{ item }}"
  with_items:
    - kubectl apply -f {{ kubernetes_flannel_manifest_file_rbac }}
    - kubectl apply -f {{ kubernetes_flannel_manifest_file }}
  register: flannel_result
  changed_when: "'created' in flannel_result.stdout"

- name: Get the kubeadm join command.
  command: kubeadm token create --print-join-command
  changed_when: false
  register: kubernetes_join_command_result