apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o k3s-manifests/ --volumes persistentVolumeClaim
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: game-server
  name: game-server
spec:
  ports:
    - name: "25565"
      port: 25565
      targetPort: 25565
  selector:
    io.kompose.service: game-server
