apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: game-server-data
  name: game-server-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
