apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: lobby-data
  name: lobby-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
