apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o k3s-manifests/ --volumes hostPath
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: proxy
  name: proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: proxy
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -o k3s-manifests/ --volumes hostPath
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: proxy
    spec:
      containers:
        - env:
            - name: MYSQL_DATABASE
              value: minecraft
            - name: MYSQL_HOST
              value: mysql
            - name: MYSQL_PASSWORD
              value: minecraft
            - name: MYSQL_PORT
              value: "3306"
            - name: MYSQL_USER
              value: minecraft
          image: proxy
          name: proxy
          ports:
            - containerPort: 25577
              protocol: TCP
            - containerPort: 25565
              protocol: TCP
          volumeMounts:
            - mountPath: /server
              name: proxy-data
            - mountPath: /server/compiled_plugins
              name: proxy-hostpath1
      restartPolicy: Always
      volumes:
        - hostPath:
            path: /home/toto/Documents/Github/perso/SAE503/src
          name: proxy-data
        - hostPath:
            path: /home/toto/Documents/Github/perso/SAE503/src/plugin/compiled_code/velocity
          name: proxy-hostpath1
