# --------------------------------------
# -- Install kubernetes runtime
# --------------------------------------
---
- name: Install Kubernetes
  block:
    - name: Disable swap
      shell:
        cmd: |
          swapoff -a
      args:
        executable: /bin/bash

    - name: Remove Swap from fstab
      mount:
        name: swap
        fstype: swap
        state: absent

    - name: Prepare system for installation
      include_tasks: ./system-setup.yaml

    - name: Let iptables see bridged traffic
      sysctl:
        name: "{{ item }}"
        value: "1"
        state: present
      loop:
        - net.bridge.bridge-nf-call-iptables
        - net.bridge.bridge-nf-call-ip6tables
        - net.ipv4.ip_forward

    - name: Install Kubernetes packages.
      package:
        name: "{{ item }}"
        state: present
      loop: "{{ kubernetes_packages }}"

    - name: Check for existence of kubelet environment file.
      stat:
        path: "{{ kubelet_environment_file_path }}"
      register: kubelet_environment_file

    - name: Set facts for KUBELET_EXTRA_ARGS task if environment file exists.
      set_fact:
        kubelet_args_path: "{{ kubelet_environment_file_path }}"
        kubelet_args_line: "{{ 'KUBELET_EXTRA_ARGS=' + kubernetes_kubelet_extra_args }}"
        kubelet_args_regexp: "^KUBELET_EXTRA_ARGS="
      when: kubelet_environment_file.stat.exists

    - name: Set facts for KUBELET_EXTRA_ARGS task if environment file doesn't exist.
      set_fact:
        kubelet_args_path: "/etc/systemd/system/kubelet.service.d/10-kubeadm.conf"
        kubelet_args_line: '{{ ''Environment="KUBELET_EXTRA_ARGS='' + kubernetes_kubelet_extra_args + ''"'' }}'
        kubelet_args_regexp: '^Environment="KUBELET_EXTRA_ARGS='
      when: not kubelet_environment_file.stat.exists

    - name: Configure KUBELET_EXTRA_ARGS.
      lineinfile:
        path: "{{ kubelet_args_path }}"
        line: "{{ kubelet_args_line }}"
        regexp: "{{ kubelet_args_regexp }}"
        state: present
        mode: 0644
      register: kubelet_config_file

    - name: Reload systemd unit if args were changed.
      systemd:
        state: restarted
        daemon_reload: true
        name: kubelet
      when: kubelet_config_file is changed

    - name: Ensure kubelet is started and enabled at boot.
      service:
        name: kubelet
        state: started
        enabled: true

    - name: Install kubectl.
      package:
        name: kubectl
        state: present
      when: node_type == 'master'
  tags: init, kubernetes

- name: Install Kubernetes
  block:
    - name: Deploy master nodes
      include_tasks: ./nodes/init-master-node.yaml
      when: node_type == 'master'

    - name: Set the kubeadm join command globally
      set_fact:
        kubernetes_join_command: >
          {{ kubernetes_join_command_result.stdout }}
          {{ kubernetes_join_command_extra_opts }}
      when: kubernetes_join_command_result.stdout is defined
      delegate_to: "{{ item }}"
      delegate_facts: true
      loop: "{{ groups['all'] }}"

    - name: Join master nodes
      include_tasks: ./nodes/join-worker-node.yaml
      when: node_type == 'worker'
  tags: deploy, kubernetes
