---
- name: Initialize Kubernetes cluster
  command: >
    kubeadm init
    --pod-network-cidr={{ pod_network_cidr }}
    --ignore-preflight-errors=all
    --kubernetes-version=v{{ kubernetes_version }}
    --v=5 # debug level
    --cri-socket=unix:///var/run/containerd/containerd.sock
  args:
    creates: /etc/kubernetes/admin.conf
  register: kubeadm_init_result

# Debug output
- name: Display kubeadm init output
  debug:
    var: kubeadm_init_result.stdout_lines

- name: Create .kube directory for root user
  file:
    path: /root/.kube
    state: directory
    mode: '0755'

- name: Copy admin.conf to root's .kube directory
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /root/.kube/config
    remote_src: yes

- name: Install Flannel network plugin
  command: kubectl apply -f https://raw.githubusercontent.com/flannel-io/flannel/master/Documentation/kube-flannel.yml
  args:
    creates: /etc/cni/net.d/10-flannel.conflist

- name: Get join command
  command: kubeadm token create --print-join-command
  register: join_command

- name: Set join command fact
  set_fact:
    join_command: "{{ join_command.stdout_lines[0] }}"