---
- name: Initialize Kubernetes cluster
  command: kubeadm init --pod-network-cidr={{ pod_network_cidr }}
  args:
    creates: /etc/kubernetes/admin.conf

- name: Create .kube directory for root user
  file:
    path: /root/.kube
    state: directory
    mode: '0755'

- name: Copy admin.conf to root's .kube directory
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /root/.kube/config
    remote_src: yes

- name: Install Calico network plugin
  command: kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml
  args:
    creates: /etc/cni/net.d/10-calico.conflist

- name: Get join command
  command: kubeadm token create --print-join-command
  register: join_command

- name: Set join command fact
  set_fact:
    join_command: "{{ join_command.stdout_lines[0] }}"