---
- name: Stop AppArmor service
  become: true
  service:
    name: apparmor
    state: stopped
    enabled: no

- name: Disable AppArmor from starting on boot
  become: true
  systemd:
    name: apparmor
    enabled: no

- name: Purge AppArmor packages
  become: true
  apt:
    name:
      - apparmor
      - apparmor-utils
    state: absent
    purge: yes
    update_cache: yes

- name: Remove remaining AppArmor configuration files
  become: true
  apt:
    autoremove: yes
    purge: yes

- name: Reboot the system to apply changes
  become: true
  reboot:
    msg: "Rebooting to complete AppArmor removal"
    connect_timeout: 5
    reboot_timeout: 600
    pre_reboot_delay: 0
    post_reboot_delay: 60
    test_command: whoami