services:
  mysql:
    build: ./server/mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: minecraft
      MYSQL_USER: minecraft
      MYSQL_PASSWORD: minecraft
    volumes:
      - ./volumes/mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 5
    networks:
      - minecraft

  maven:
    build: ./plugin/maven
    container_name: maven
    volumes:
      - ./plugin/compiled_code/paper:/app/compiled_code/paper
      - ./plugin/compiled_code/velocity:/app/compiled_code/velocity
      - ./plugin/source_code/paper:/app/source_code/paper
      - ./plugin/source_code/velocity:/app/source_code/velocity

  gradle:
    build: ./plugin/gradle
    container_name: gradle
    volumes:
      - ./plugin/compiled_code/paper:/app/compiled_code/paper
      - ./plugin/compiled_code/velocity:/app/compiled_code/velocity
      - ./plugin/source_code/paper:/app/source_code/paper
      - ./plugin/source_code/velocity:/app/source_code/velocity

  game-server:
    build: 
      context: ./
      dockerfile: ./server/common/game-server-files/Dockerfile
    volumes:
      - game-server:/data
      - ./plugin/compiled_code/paper:/data/compiled_plugins
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=minecraft
      - MYSQL_USER=minecraft
      - MYSQL_PASSWORD=minecraft
    depends_on:
      mysql:
        condition: service_healthy
      maven:
        condition: service_completed_successfully
      gradle:
        condition: service_completed_successfully
    networks:
      - minecraft

  lobby:
    build: 
      context: ./
      dockerfile: ./server/common/lobby-files/Dockerfile
    volumes:
      - lobby-data:/data
      - ./plugin/compiled_code/paper:/data/compiled_plugins
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=minecraft
      - MYSQL_USER=minecraft
      - MYSQL_PASSWORD=minecraft
    depends_on:
      mysql:
        condition: service_healthy
      game-server:
        condition: service_started
    networks:
      - minecraft

  proxy:
    build: 
      context: ./
      dockerfile: ./server/common/proxy-files/Dockerfile
    ports:
      - "25565:25577"
    volumes:
      - proxy-data:/server
      - ./plugin/compiled_code/velocity:/server/compiled_plugins
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=minecraft
      - MYSQL_USER=minecraft
      - MYSQL_PASSWORD=minecraft
    depends_on:
      game-server:
        condition: service_started
      lobby:
        condition: service_started
    networks:
      - minecraft

volumes:
  game-server:
  lobby-data:
  proxy-data:

networks:
  minecraft:
