---
- name: Deploy vagrant
  ansible.builtin.command: vagrant up --provision
  args:
    chdir: "{{ vagrant_file_path }}"
  register: vagrant_result
  changed_when: vagrant_result.rc == 0

- name: Get Vagrant VM IP address
  ansible.builtin.command: vagrant ssh -c "hostname -I | cut -d' ' -f1"
  args:
    chdir: "{{ vagrant_file_path }}"
  register: vagrant_ip
  changed_when: false

- name: Set fact for Vagrant IP
  ansible.builtin.set_fact:
    vagrant_vm_ip: "{{ vagrant_ip.stdout.strip() }}"

- name: Debug Vagrant IP
  ansible.builtin.debug:
    var: vagrant_vm_ip
