---
- name: Install vagrant
  ansible.builtin.include_tasks: install_vagrant.yml

- name: Configure vagrant box
  ansible.builtin.include_tasks: configure_vagrant_box.yml

- name: Configure vagrant
  ansible.builtin.include_tasks: configure_vagrant.yml

- name: Deploy vagrant
  ansible.builtin.include_tasks: deploy_vagrant.yml

- name: Update inventory
  ansible.builtin.include_tasks: update_inventory.yml
