---
- name: Include master vars
  ansible.builtin.include_vars: masters.yml
  when: "'masters' in groups and inventory_hostname in groups['masters']"

- name: Include worker vars
  ansible.builtin.include_vars: workers.yml
  when: "'workers' in groups and inventory_hostname in groups['workers']"

- name: Install vagrant
  ansible.builtin.include_tasks: install_vagrant.yml

- name: Configure vagrant box
  ansible.builtin.include_tasks: configure_vagrant_box.yml

- name: Configure vagrant
  ansible.builtin.include_tasks: configure_vagrant.yml

- name: Deploy vagrant
  ansible.builtin.include_tasks: deploy_vagrant.yml

- name: Update inventory
  ansible.builtin.include_tasks: update_inventory.yml
