# --------------------------------------
# -- Prepare system
# -- for containerd installation
# --------------------------------------
# -- Implemented:
# ---- Debian
# --------------------------------------
---
# --------------------------------------
# -- Debian
# --------------------------------------
- name: Prepare Debian
  block:
    - name: Add the overlay and br_netfilter modules
      modprobe:
        name: "{{ item }}"
        state: present
      loop:
        - "overlay"
        - "br_netfilter"

    - name: Update and upgrade all packages
      ansible.builtin.apt:
        update_cache: yes
        upgrade: full

    - name: Ensure dependencies are installed
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg2
        state: present
        update_cache: yes

    - name: Create keyrings directory
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Download Docker's official GPG key
      get_url:
        url: https://download.docker.com/linux/debian/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: '0644'

    - name: Add Docker repository
      apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
        state: present
        filename: docker
  tags: init, cri, system
  when: ansible_os_family == 'Debian'
