# --------------------------------------
# -- Install container runtime
# --------------------------------------
# -- Implemeneted:
# ---- Containerd
# --------------------------------------
---
# --------------------------------------
# -- Containerd
# --------------------------------------
- name: Install containerd
  block:
    - name: Prepare system
      include_tasks: ./containerd/system-setup.yaml

    - name: Ensure containerd is installed.
      package:
        name: containerd.io
        state: present

    - name: Ensure containerd is started and enabled at boot.
      service:
        name: containerd
        state: started
        enabled: true

    - name: Ensure containerd config directory exists.
      file:
        path: /etc/containerd
        state: directory
      register: containerd_dir

    - name: Get defaults from containerd.
      command: containerd config default
      changed_when: false
      register: containerd_config_default
      when: containerd_config_default_write

    - name: Write defaults to config.toml.
      copy:
        dest: /etc/containerd/config.toml
        content: "{{ containerd_config_default.stdout }}"
      notify: restart containerd
      when: containerd_config_default_write
  tags: init, cri
  when: container_runtime == 'containerd'
