# --------------------------------------
# -- Install container runtime
# --------------------------------------
# -- Implemeneted:
# ---- Containerd
# --------------------------------------
---
# --------------------------------------
# -- Containerd
# --------------------------------------
- name: Install containerd
  block:
    - name: Prepare system
      include_tasks: ./containerd/system-setup.yaml

    - name: Ensure containerd is installed.
      package:
        name: containerd.io
        state: present

    - name: Ensure containerd is started and enabled at boot.
      service:
        name: containerd
        state: started
        enabled: true

    - name: Ensure containerd config directory exists.
      file:
        path: /etc/containerd
        state: directory
      register: containerd_dir

    - name: Generate default containerd configuration
      command: containerd config default
      register: containerd_config_default

    - name: Write default containerd config to config.toml
      copy:
        dest: /etc/containerd/config.toml
        content: "{{ containerd_config_default.stdout }}"
      notify: restart containerd

    - name: Create crictl configuration file
      copy:
        dest: /etc/crictl.yaml
        content: |
          runtime-endpoint: unix:///run/containerd/containerd.sock
  tags: init, cri
  when: container_runtime == 'containerd'
