#!/usr/bin/env bash
set -uo pipefail
IFS=$'\n\t'

# Load utility methods
. "$ROOT_DIR/utils"

function cleanup() {
    echo "Cleaning up..."
}

if [[ "${BASH_SOURCE[0]}" = "$0" ]]; then
    trap cleanup EXIT

    path=`$cli_name_app zoptions rc read .dir`
    cd ${path}

    # Ask for SSH user and IP
    read -p "Enter the SSH user: " ssh_user
    read -p "Enter the IP address: " ip_address

    # Copy the SSH public key to the remote host
    ssh-copy-id -i ../keys/id_rsa.pub "${ssh_user}@${ip_address}"

    if [ $? -eq 0 ]; then
        echo "SSH key successfully copied to ${ssh_user}@${ip_address}"
    else
        echo "Failed to copy SSH key. Please check the user and IP address and try again."
    fi
fi